---
#
# CI configuration for Onionbalance
#

#
# General
#

# CI Templates
include:
  # Onion MkDocs
  - project: tpo/web/onion-mkdocs
    file: .gitlab-ci-base.yml

  # APT configuration
  - project: tpo/tpa/ci-templates
    file: scripts/apt.yml

  # Debian packaging
  - project: tpo/onion-services/ci-templates
    file: onion-services/debian.yml

  # Python packaging
  - project: tpo/onion-services/ci-templates
    file: onion-services/python.yml

  # GitLab releases
  - project: tpo/onion-services/ci-templates
    file: onion-services/release.yml

# Default image
image: containers.torproject.org/tpo/tpa/base-images/python:sid

variables:
  # Use full clone so "./onionbalance.py --version" works
  # https://docs.gitlab.com/ci/runners/configure_runners/#git-strategy
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

.base:
  before_script:
    - pip3 install -r requirements.txt --break-system-packages
    - pip3 install -r test-requirements.txt  --break-system-packages
    - python3 -m pip install . --break-system-packages

#
# Basic build
#

install:
  stage: build
  extends: .base
  script:
    - /bin/true

#
# Python
#

# Needs Git installed so "./onionbalance.py --version" works
python:
  !reference [.python]

#
# Tests
#

functional_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance test/functional/

unit_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance --ignore=test/functional/

static_tests:
  stage: test
  extends: .base
  script:
    - pylint onionbalance --disable=R,C,W

style_tests:
  stage: test
  extends: .base
  script:
    - flake8 onionbalance

config_tests:
  stage: test
  extends: .base
  script:
    - ./onionbalance-config.py --no-interactive
    - ls config/*.key
    - cat config/config.yaml

run_test:
  stage: test
  extends: .base
  script:
    # Needs Git installed so "./onionbalance.py --version" works
    - !reference [.apt-init]
    - apt-get install -y git
    - git describe --tags --dirty --always --long
    - ./onionbalance.py --version

#
# Debian
#

debian_stable:
  !reference [.debian-stable]

debian_sid:
  !reference [.debian-sid]

ubuntu_lts:
  !reference [.ubuntu-lts]

lintian:
  !reference [.lintian]

piuparts:
  !reference [.piuparts]

#
# Documentation
#

pages:
  stage: deploy
  extends: .onion-mkdocs-clone
  after_script:
    - $ONION_MKDOCS_LOCATION/scripts/onion-mkdocs-provision-build
    - $ONION_MKDOCS_LOCATION/scripts/onion-mkdocs-build
    - scripts/docs-preserve-historic-urls
