---
image: containers.torproject.org/tpo/tpa/base-images/python:bookworm
include:
  - project: tpo/web/onion-mkdocs
    file: .gitlab-ci-base.yml
  - project: tpo/tpa/ci-templates
    file: scripts/apt.yml

#variables:
#  # Use full clone so "./onionbalance.py --version" works
#  # https://docs.gitlab.com/ci/runners/configure_runners/#git-strategy
#  GIT_STRATEGY: clone
#  GIT_DEPTH: 0

stages:
  - setup
  - test
  - deploy

.base:
  before_script:
    - pip3 install -r requirements.txt --break-system-packages
    - pip3 install -r test-requirements.txt  --break-system-packages
    - python3 -m pip install . --break-system-packages

install:
  stage: setup
  extends: .base
  script:
    - /bin/true

functional_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance test/functional/

unit_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance --ignore=test/functional/

static_tests:
  stage: test
  extends: .base
  script:
    - pylint onionbalance --disable=R,C,W

style_tests:
  stage: test
  extends: .base
  script:
    - flake8 onionbalance

config_tests:
  stage: test
  extends: .base
  script:
    - ./onionbalance-config.py --no-interactive
    - ls config/*.key
    - cat config/config.yaml

run_tests:
  stage: test
  extends: .base
  script:
    - !reference [.apt-init]
    - apt-get install -y git
    - git describe
    - ./onionbalance.py --version

pages:
  stage: deploy
  extends: .onion-mkdocs-clone
  after_script:
    - $ONION_MKDOCS_LOCATION/scripts/onion-mkdocs-provision-build
    - $ONION_MKDOCS_LOCATION/scripts/onion-mkdocs-build
    - scripts/docs-preserve-historic-urls

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: .post
  rules:
    # Run this job when a tag is created
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running release_job..."
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
