---
image: python:bookworm
include:
  project: tpo/web/onion-mkdocs
  file: .gitlab-ci-base.yml

stages:
  - setup
  - test
  - deploy

.base:
  before_script:
    - pip3 install -r requirements.txt --break-system-packages
    - pip3 install -r test-requirements.txt  --break-system-packages
    - python3 -m pip install . --break-system-packages

install:
  stage: setup
  extends: .base
  script:
    - /bin/true

functional_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance test/functional/

unit_tests:
  stage: test
  extends: .base
  script:
    - pytest --cov-report=term-missing --cov=onionbalance --ignore=test/functional/

static_tests:
  stage: test
  extends: .base
  script:
    - pylint onionbalance --disable=R,C,W

style_tests:
  stage: test
  extends: .base
  script:
    - flake8 onionbalance

pages:
  stage: deploy
  extends: .onion-mkdocs-clone
  after_script:
    - $ONION_MKDOCS_LOCATION/scripts/onion-mkdocs-provision-build
    - $ONION_MKDOCS_LOCATION/scripts/onion-mkdocs-build
    - scripts/docs-preserve-historic-urls
