# Read the Docs configuration file for Sphinx projects
# Check https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Disable the build process as documentation was migrated.
#
# This will trigger a config validation error, so the build process
# at Read the Docs don't go further (and hence we save them CPU cycles).
#
# Check https://gitlab.torproject.org/tpo/onion-services/onionbalance/-/issues/28
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - false

# Build docs using Onion MkDocs
#build:
#  os: ubuntu-22.04
#  tools:
#    python: "3.12"
#  apt_packages:
#    - mkdocs
#    - pipenv
#  jobs:
#    pre_install:
#      # Vendorize Onion MkDocs
#      - rm -rf vendors/onion-mkdocs
#      - mkdir -p vendors/
#      - git clone https://gitlab.torproject.org/tpo/web/onion-mkdocs.git vendors/onion-mkdocs
#
#      # Install dependencies
#      #- vendors/onion-mkdocs/scripts/onion-mkdocs-provision-build
#      - PIPENV_PIPFILE=vendors/onion-mkdocs/Pipfile pipenv install
#
#      # Convert the Pipfile into requirements.txt, so Read the Docs can install
#      # the dependencies
#      - PIPENV_PIPFILE=vendors/onion-mkdocs/Pipfile pipenv requirements
#
#    post_build:
#      # Do the entire build process again in the post_build phase, since we
#      # use a customized procedure
#      - rm -rf public
#      - vendors/onion-mkdocs/scripts/onion-mkdocs-build
#      - scripts/docs-preserve-historic-urls
#
#python:
#  install:
#    # Use the requirements.txt generated by pipenv
#    - requirements: requirements.txt
#
#mkdocs:
#  configuration: mkdocs.yml
