language: python
sudo: required
dist: bionic
python: 3.7
env:
  - TOXENV=py37 TEST=unit
#  - TOXENV=py37 TEST=functional_v2
#  - TOXENV=py37 TEST=functional_v3
  - TOXENV=style
  - TOXENV=docs
before_install:
  # Install tor and chutney if doing functional tests
  - if [[ $TEST == functional* ]]; then ./test/scripts/install-tor.sh; fi
  - if [[ $TEST == 'functional_v2' ]]; then source test/scripts/install-chutney-v2.sh; fi
  - if [[ $TEST == 'functional_v3' ]]; then source test/scripts/install-chutney-v3.sh; fi
install:
  - pip install tox coveralls
script:
  - if [[ $TEST == 'functional_v2' ]]; then tox ./test/functional/v2/;
   elif [[ $TEST == 'functional_v3' ]]; then tox ./test/functional/v3/;
   elif [[ $TEST == 'unit' ]]; then tox -- --ignore=./test/functional/;
   else tox; fi
after_success:
  - coveralls
